### ISSUE TITLE
劇の名前をclassroomに紐づける

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#166]
これもUX向上目的です。

**Comment by coord-e** [comment]
epic?

**Comment by Cj-bc** [comment]
これ、jsonにするかとかの議論もあり、その場合大幅な変更もあるためepic
コードの中に直接名前を埋め込むのもどうなものかと...

**Comment by coord-e** [comment]
理解

**Comment by Cj-bc** [comment]
`json`ファイルにして、作成しますね
大きい気がしていたけど、整理するとそこまでではないかもしれません。
Todo出来次第投下します、作展に間に合うかはわからない
frontとの兼ね合いもあるのでおそらく間に合わないとは思いますが...

**Comment by Cj-bc** [comment]
## definitions

### classrooms.json

```python
{
    "0": {
                "grade": <int:grade>,
                "index": <int:index>,
                "title": <str:title_of_the_show>
    },
    "1": 
                "grade": <int:grade>,
                "index": <int:index>,
                "title": <str:title_of_the_show>
    }, ...
}
```
## workflow

1. `classrooms.json`からクラスルームを取得
2. `api/app.py`内`generate()`で`classroom`を作成する際、`1.`で得た情報を追加して作成する。
3. `classroom_schema`にフィールドを追加する

## Todo

- [ ] `classrooms.json`作成
- [ ] `classrooms.json`読み込み
- [ ] `api/app.py`編集
- [ ] クラスと劇の名前をどこからか取得
- [ ] `classroom_schema`編集
- [ ] `test_classrooms_correct_title`追加
