### ISSUE TITLE
発表用媒体(PDF, etc)を返すエンドポイントを作成

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/backend#183]
Step 1: 目的
============

* 発表用に印刷するファイルを作成し、返す

Step 2: 概要
============

 * 仕様: 一個前のtime_indexの各lotteryのwinnersのpublic_idを、classroomごとにわけ、かつその中でstudent/visitorで分けて印刷可能にしたものを返す。作成した媒体はキャッシュする。
 * 既に作成されている場合は、キャッシュされたものを返す
 * エンドポイント名は、`PDFという文字列を含まないもの`

* rfc: Sakuten/rfcs#2

タスク:
=======

- [x] 返す形式を決定(PDF or html)
- [x] PDF or HTMLのテンプレートを作成する(おそらくjinja)
  - [x] `html`部分の作成
  - [x] `css`部分の作成
- [x] エンドポイント名を決定
- [x] 権限範囲決定 ( Sakuten/rfcs#2)
- [x] `spec`作成
- [x] エンドポイントを作成
  - [x] 1. Get previous time index                                             
  - [x] 2. Get previous lotteries using index                                  
  - [x] 5. Make 2 public_id lists, based on user's 'kind'('student', 'visitor')
  - [x] 6. Send them to the jinja template

- [x] `get_prev_time_index`追加
- [x] test作成
  - [x] test: test_prev_time_index_ooa
  - [x] test: test_prev_time_index_lim
  - [x] test: test_prev_time_index_same

決定事項:
========

* 形式: ~~PDF~~ HTML(システムの都合上PDF化は時間がかかりそうでした)
* PDFを出力する: pdfkit
* エンドポイント名: `/render_results`
* HTTP method: `GET`
* 権限制約: なし
* 時間外だった場合のエラーコードおよびstatus code
  * error_code: `06`
  * HTTP status code: `400`
  * error_message: `not acceptable time`

**Comment by Cj-bc** [comment]
HTTP method: `GET`
path: `/results`

**Comment by Cj-bc** [comment]
rfc has been opened Sakuten/rfcs#2

**Comment by Cj-bc** [comment]
権限範囲は決定しないことになりました。

**Comment by Cj-bc** [comment]
時間外だった場合のエラーコードおよびstatus code
error_code: `06`
HTTP status code: `404`
error_message: `not acceptable time`

**Comment by Cj-bc** [comment]
### `get_prev_time_index`仕様

* ある`index`の応募受付時間終了時+1分〜次回の応募受付時間終了時+1分までの間、その`index`を返します

**Comment by coord-e** [comment]
時間外、400では？

**Comment by Cj-bc** [comment]
あ、ほんとだww
単純なミスですありがと

**Comment by Cj-bc** [comment]
### `template`作成について

* 横に並べられるIDの数はいくつか
* `kind`で分けて発表とあるが、紙を分けて発表するという認識で合っているか

**Comment by Cj-bc** [comment]
配列の分け方:
```python
visitor = [{'classroom_id': lottery.classroom_id, 'winners': [winner.public_id, winner.public_id,...]}, {'classroom_id': lottery.classroom_id, 'winners': [winner.public_id, winner.public_id,...]},...]
student = [{'classroom_id': lottery.classroom_id, 'winners': [winner.public_id, winner.public_id,...]}, {'classroom_id': lottery.classroom_id, 'winners': [winner.public_id, winner.public_id,...]},...]

**Comment by Cj-bc** [comment]
データ構造的によろしくないかもしれませんが、ちょっと進ませてくだせぇ..

**Comment by Cj-bc** [comment]
配列の分け方、リファクタリングが必要な部分です。
```python
data = {'kinds':                                                         
          [{'visitor':                                                   
              [{'classroom_id': lottery.classroom_id,                    
                'winners': [lottery.application.user(has 'visitor' kind)]
               }],                                                       
            'student':                                                   
              [{'classroom_id': lottery.classroom_id,                    
                'winners': [lottery.application.user(has 'student' kind)]
               }]                                                        
           }]                                                            
       }                                                                 
```

**Comment by Cj-bc** [comment]
**PDFきつそうなので一度HTMLで返します**
PDFきつい理由: `wkhtmltopdf`が、`alpine`上でcss適用がうまくできないという情報を取得したから
参考:
https://gist.github.com/akihiromukae/288b163d538d45a197b3f1b54ef385e8

PDFで返すissueも立てておきますが、`first_release`後になる可能性があります

**Comment by Cj-bc** [comment]
又、HTMLに変更したことにより、cacheを持つ必要も無くなったので、cache関連のtodoを削除します

**Comment by Cj-bc** [comment]
🤔 
あとはcss書けば終わりです

**Comment by tamazasa** [comment]
A0サイズををCSSで表現するとき
仕様では841mmですが、それだとはみ出ます
適正サイズはフォントサイズによって変わるようです
小さめに調整します

**Comment by Cj-bc** [comment]
close with merging of #212
