### ISSUE TITLE
一日目で使ったIDを二日目で使えないというときにそういうエラーを返す

### ISSUE THREAD

**Issue by coord-e** [Sakuten/backend#199]
Step 1: 目的
============

 * 同じカード使っちゃうの、よくあるミスな気がするので、親切にやっていきたい

Step 2: 概要
============

 * 新しいエラー
 * Login Unsuccessfulじゃないやつ。
 * できれば本番に間に合わせたいかな。

**Comment by Cj-bc** [comment]
...となると`todays_user`の変更が必要そうですね
やりまふ

**Comment by Cj-bc** [comment]
これなのですが、`ユーザーIDが見つからなかった`場合のエラーを`error_num: 5`の`No such user found`に変えようか悩んでいます。
変えると、これまでは`400`で返っていた(これまでは`3`の`Login Unsuccessful`だった)から`404`に変わってしまうため、どうなんだろうというお気持ちです...
どう思いますか、他の方

**Comment by Cj-bc** [comment]
## Todo

- [ ] `todays_user`の書き換え
- [ ] `api/routes/auth`書き換え
- [ ] `api/routes/api`書き換え
- [ ] `test/test_users`書き換え（場合による）

**Comment by Cj-bc** [comment]
もう一箇所、`login_required`内なのですが、80,81行目、`todays_user`でユーザーが見つからなかった場合（=無効化されている場合）に`401 -- Unauthorized`を返し`realm`で`ID disabled`として伝えていますが、これは変えないべきでしょうか...?
個人的には変えないべきだとは思うのですけれど、同じエラーに対して複数の表示があるのもおかしいなぁとも思います。
@Sakuten/moderator

**Comment by Cj-bc** [comment]
PR: #210
